# Generated by Django 2.1.5 on 2019-02-24 11:04

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hemeroteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('fecha_noticia', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('imagen', models.ImageField(upload_to='Hemeroteca', verbose_name='Imagen hemeroteca')),
            ],
            options={
                'verbose_name': 'hemeroteca',
                'verbose_name_plural': 'hemerotecas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
