# Generated by Django 2.1.5 on 2019-02-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hemeroteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hemeroteca',
            old_name='fecha_noticia',
            new_name='fecha',
        ),
    ]
