# Generated by Django 2.1.5 on 2019-02-18 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'noticia', 'verbose_name_plural': 'noticias'},
        ),
        migrations.AddField(
            model_name='noticia',
            name='fecha_notica',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha modificación'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(upload_to='Noticia', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(max_length=200, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
