# Generated by Django 2.1.5 on 2019-02-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_auto_20190218_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='fecha_notica',
            new_name='fecha_noticia',
        ),
    ]
