# Generated by Django 2.1.7 on 2019-02-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0004_auto_20190222_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='memoria',
            field=models.FileField(blank=True, null=True, upload_to='Memorias', verbose_name='Memoria'),
        ),
    ]
