# Generated by Django 2.1.7 on 2019-02-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0005_noticia_memoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='memoria',
        ),
    ]
