# Generated by Django 2.1.5 on 2019-02-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0006_remove_noticia_memoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='localizacion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Localización'),
        ),
    ]
