# Generated by Django 2.1.5 on 2019-02-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0007_noticia_localizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase_Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to='Noticia', verbose_name='Imagen principal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imágenes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(upload_to='Noticia', verbose_name='Imagen principal'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='publicacion_imagenes',
            field=models.ManyToManyField(to='noticia.Clase_Imagen', verbose_name='Imágenes'),
        ),
    ]
