# Generated by Django 2.1.5 on 2019-02-23 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0008_auto_20190223_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='publicacion_imagenes',
        ),
        migrations.DeleteModel(
            name='Clase_Imagen',
        ),
    ]
