# Generated by Django 2.1.5 on 2019-02-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0009_auto_20190223_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen 2'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen 3'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen 4'),
        ),
    ]
