# Generated by Django 2.1.5 on 2019-02-23 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0010_auto_20190223_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='subtitulo',
        ),
    ]
