# Generated by Django 2.1.5 on 2019-02-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0011_remove_noticia_subtitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen10',
            field=models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen 10'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen5',
            field=models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen 5'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen6',
            field=models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen 6'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen7',
            field=models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen 7'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen8',
            field=models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen 8'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen9',
            field=models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen 9'),
        ),
    ]
