# Generated by Django 2.1.5 on 2019-02-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0012_auto_20190224_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre fotografía')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
            ],
            options={
                'verbose_name': 'fotografía',
                'verbose_name_plural': 'fotografías',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagenes',
            field=models.ManyToManyField(related_name='get_fotografias', to='noticia.Fotografias', verbose_name='Fotografías'),
        ),
    ]
