# Generated by Django 2.1.5 on 2019-02-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0013_auto_20190224_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografias',
            name='imagen_foto',
            field=models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen principal'),
        ),
    ]
