# Generated by Django 2.1.5 on 2019-02-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0014_fotografias_imagen_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagenes',
        ),
        migrations.DeleteModel(
            name='Fotografias',
        ),
    ]
