# Generated by Django 2.1.5 on 2019-02-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0015_auto_20190224_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagen10',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagen3',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagen4',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagen5',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagen6',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagen7',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagen8',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagen9',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(upload_to='Noticia', verbose_name='Imagen Noticia'),
        ),
    ]
