# Generated by Django 2.1.5 on 2019-02-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0016_auto_20190224_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='localizacion',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='Localización'),
        ),
    ]
