# Generated by Django 2.1.5 on 2019-03-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0017_auto_20190224_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen2'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen3'),
        ),
    ]
