# Generated by Django 2.1.5 on 2019-03-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0018_auto_20190302_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagen3',
        ),
    ]
