# Generated by Django 2.1.5 on 2019-03-02 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0022_albumimagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumimagen',
            name='album',
        ),
        migrations.AddField(
            model_name='noticia',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='noticia.AlbumImagen'),
        ),
    ]
