# Generated by Django 2.1.5 on 2019-03-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0023_auto_20190302_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='album',
        ),
        migrations.AddField(
            model_name='noticia',
            name='album',
            field=models.ManyToManyField(blank=True, null=True, related_name='images', to='noticia.AlbumImagen'),
        ),
    ]
