# Generated by Django 2.1.5 on 2019-03-02 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0027_auto_20190302_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumimagen',
            name='imagen1',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='noticia.AlbumImagen'),
        ),
    ]
