# Generated by Django 2.1.5 on 2019-03-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0028_auto_20190302_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimagen',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen principal'),
        ),
    ]
