# Generated by Django 2.1.5 on 2019-03-02 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0029_albumimagen_imagen1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('imagen1', models.ImageField(upload_to='Noticia', verbose_name='Imagen principal')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen 2')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen 3')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen 4')),
                ('imagen5', models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen 5')),
                ('imagen6', models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen 6')),
                ('imagen7', models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen 7')),
                ('imagen8', models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen 8')),
                ('imagen9', models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen 9')),
                ('imagen10', models.ImageField(blank=True, null=True, upload_to='Noticia', verbose_name='Imagen 10')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imagenes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterField(
            model_name='noticia',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='noticia.Album'),
        ),
        migrations.DeleteModel(
            name='AlbumImagen',
        ),
    ]
